version: '3'

services:
  mlrepo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        gitUsername: sHarshil-Shah
        gitPass: xxxxxxxxx #if password contains @, use %40 instead
    volumes:
     - ml_storage:/root/docker-compose-files/ml/docker-storage

volumes:
 ml_storage:

